### ISSUE TITLE
App crashes when Cloudy is used in a ModalBottomSheet

### ISSUE THREAD

**Issue by Rick-AB** [skydoves/Cloudy#14]
**Please complete the following information:**
- Library Version v0.1.2
- Affected Device(s) Samsung S20(API 33), Pixel 4(API 33)
 
**Describe the Bug:**

When cloudy is used as a component inside a ModalBottomSheet, the exception `java.lang.RuntimeException: Failed to copy pixels of the given bitmap!`  is thrown

**Expected Behavior:**

The application shouldn't crash

**Comment by AndreyMedal** [comment]
Have the same problem in preview:

```
FATAL EXCEPTION: main
                                                                                                    Process: com.test.app, PID: 9114
                                                                                                    java.lang.RuntimeException: Failed to copy pixels of the given bitmap!
                                                                                                    	at com.skydoves.cloudy.CloudyKt.drawBitmapWithPixelCopy$lambda$7(Cloudy.kt:281)
                                                                                                    	at com.skydoves.cloudy.CloudyKt.$r8$lambda$X2Nw-BPO6_ca_Hnlrx5we4hyARg(Unknown Source:0)
                                                                                                    	at com.skydoves.cloudy.CloudyKt$$ExternalSyntheticLambda0.onPixelCopyFinished(Unknown Source:6)
                                                                                                    	at android.view.PixelCopy$1.run(PixelCopy.java:191)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8757)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by iamcodder** [comment]
Have the same problem

**Comment by HolenZhou** [comment]
Have the same problem

**Comment by bybozyurt** [comment]
Have the same problem

**Comment by skydoves** [comment]
Hey guys, the new version 0.2.0 has been released, and now you can resolve this issue by using the `Modifier.cloudy` modifier instead of the `Cloudy` composable function.
