### ISSUE TITLE
RuntimeException: Failed to copy pixels of the given bitmap!

### ISSUE THREAD

**Issue by msusman1** [skydoves/Cloudy#22]
**Please complete the following information:**
- Library Version 0.1.2
- Affected Device(s) Pixel 7
 
**Describe the Bug:**

Application Crashing

```
java.lang.RuntimeException: Failed to copy pixels of the given bitmap!
	at com.skydoves.cloudy.CloudyKt.drawBitmapWithPixelCopy$lambda$7(Cloudy.kt:281)
	at com.skydoves.cloudy.CloudyKt.$r8$lambda$X2Nw-BPO6_ca_Hnlrx5we4hyARg(Unknown Source:0)
	at com.skydoves.cloudy.CloudyKt$$ExternalSyntheticLambda0.onPixelCopyFinished(Unknown Source:6)
	at android.view.PixelCopy$1.run(PixelCopy.java:191)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by alizeyn** [comment]
Same thing happens for me when navigating to another screen and navigating back to the screen in which `cloudy` is used.    
```
java.lang.RuntimeException: Failed to copy pixels of the given bitmap!
	at com.skydoves.cloudy.CloudyKt.drawBitmapWithPixelCopy$lambda$7(Cloudy.kt:281)
	at com.skydoves.cloudy.CloudyKt.$r8$lambda$dvLUHhx2GzqWOBNcdQYzpkyw3bE(Unknown Source:0)
	at com.skydoves.cloudy.CloudyKt$$ExternalSyntheticLambda0.onPixelCopyFinished(D8$$SyntheticClass:0)
	at android.view.PixelCopy$1.lambda$onCopyFinished$0(PixelCopy.java:193)
	at android.view.PixelCopy$1$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8819)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

**Comment by appcommerce** [comment]
@alizeyn Same happened with me. Have you found the solution?

**Comment by VeceluXa** [comment]
@alizeyn Same happened with me. Have you found the solution?

**Comment by skydoves** [comment]
Hey guys, the new version 0.2.0 has been released, and now you can resolve this issue by using the `Modifier.cloudy` modifier instead of the `Cloudy` composable function.
